### ISSUE TITLE
Create landing page layout

### ISSUE THREAD

**Issue by g00gol** [g00gol/modular-fitness-site#18]
- Create `views/layouts/landing.handlebars` that is rendered first as the `"/"` route if the user is not logged in
- Change the routing such that users that aren't logged in are redirected to the landing page

**Comment by haujla1** [comment]
I will attempt issue, this weekend.

**Comment by g00gol** [comment]
If you have any questions, please lmk!

**Comment by haujla1** [comment]
pr #25
